# Prefix
#set-option -g prefix C-t
#unbind-key C-b
#bind-key C-t send-prefix


# split window
bind - split-window -v
bind \\ split-window -h

# select pane Shift + arrow
bind -n S-left select-pane -L
bind -n S-right select-pane -R
bind -n S-up select-pane -U
bind -n S-down select-pane -D

# 3 split
bind-key 3 split-window -h \; \
       split-window -h \; \
       select-layout even-horizontal

# 3x3 grid split
bind-key 9 split-window -v -p 66 \; \
       split-window -v -p 50 \; \
       select-pane -t 0 \; \
       split-window -h -p 66 \; \
       split-window -h -p 50 \; \
       select-pane -t 3 \; \
       split-window -h -p 66 \; \
       split-window -h -p 50 \; \
       select-pane -t 6 \; \
       split-window -h -p 66 \; \
       split-window -h -p 50 \; \
       select-pane -t 0

# delete all pain except 0
bind-key 0 kill-pane -a \; resize-pane -Z
