# Prefix
#set-option -g prefix C-t
#unbind-key C-b
#bind-key C-t send-prefix


# split window
bind - split-window -v
bind \\ split-window -h

# select pane Shift + arrow
bind -n S-left select-pane -L
bind -n S-right select-pane -R
bind -n S-up select-pane -U
bind -n S-down select-pane -D
